CREATE TABLE notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id bigint NOT NULL REFERENCES users(id),
    order_id bigint REFERENCES orders(id),
    event_key varchar(200) NOT NULL,
    type varchar(50) NOT NULL,
    title varchar(160) NOT NULL,
    message varchar(500) NOT NULL,
    read_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_notifications_recipient_event UNIQUE (recipient_user_id, event_key)
);
CREATE INDEX ix_notifications_recipient_unread_created ON notifications(recipient_user_id, read_at, created_at DESC);

CREATE TABLE notification_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key varchar(200) NOT NULL UNIQUE,
    event_type varchar(50) NOT NULL,
    recipient_user_id bigint REFERENCES users(id),
    recipient_email varchar(255) NOT NULL,
    template_data text NOT NULL DEFAULT '{}',
    status varchar(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','SENDING','RETRY','SENT','FAILED')),
    attempts integer NOT NULL DEFAULT 0,
    next_attempt_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    lease_until timestamp(6) with time zone,
    sent_at timestamp(6) with time zone,
    last_error varchar(500),
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    updated_at timestamp(6) with time zone NOT NULL DEFAULT now()
);
CREATE INDEX ix_notification_outbox_due ON notification_outbox(status, next_attempt_at, lease_until);

CREATE TABLE low_stock_alert_states (
    variant_id bigint NOT NULL REFERENCES product_variants(id) ON DELETE CASCADE,
    threshold integer NOT NULL CHECK (threshold >= 0),
    active boolean NOT NULL DEFAULT false,
    updated_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (variant_id, threshold)
);
