CREATE TABLE inventory_movements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id bigint NOT NULL,
    sku varchar(255) NOT NULL,
    order_id bigint,
    movement_type varchar(32) NOT NULL CHECK (movement_type IN (
        'OPENING_STOCK', 'OPENING_BALANCE', 'SALE', 'RESERVATION', 'PAYMENT_CAPTURED',
        'RESERVATION_RELEASED', 'RESTOCKED'
    )),
    stock_delta integer NOT NULL DEFAULT 0,
    reserved_delta integer NOT NULL DEFAULT 0,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ck_inventory_movement_nonzero CHECK (stock_delta <> 0 OR reserved_delta <> 0)
);

CREATE INDEX ix_inventory_movements_variant_created
    ON inventory_movements (variant_id, created_at DESC, id DESC);
CREATE INDEX ix_inventory_movements_order
    ON inventory_movements (order_id) WHERE order_id IS NOT NULL;

-- Lưu số dư đang có tại thời điểm bật sổ, để các biến động mới có điểm bắt đầu đối chiếu.
INSERT INTO inventory_movements (variant_id, sku, movement_type, stock_delta, reserved_delta)
SELECT id, sku, 'OPENING_BALANCE', stock_quantity, reserved_quantity
FROM product_variants
WHERE stock_quantity <> 0 OR reserved_quantity <> 0;
